# Dev-only placeholder secret, see note in 02-db-secret.yaml.
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: ciid-project
type: Opaque
stringData:
  SECRET_KEY: changethis
  FIRST_SUPERUSER: admin@example.com
  FIRST_SUPERUSER_PASSWORD: changethis
